(()=>{
  'use strict';
  const root=document.getElementById('addonCards'),filters=document.getElementById('addonFilters'),quote=document.getElementById('addonQuote');
  if(!root||!filters||!quote||!window.QuMarketCart)return;
  const services=[
    {id:'qufense-extra-endpoints',category:'capacity',name:{en:'QuFense additional endpoints',es:'Endpoints adicionales QuFense'},description:{en:'Extend protected capacity without changing the base package.',es:'Amplía la capacidad protegida sin cambiar el paquete base.'},billing:'monthly',unit:'endpoint/month',unitEs:'endpoint/mes',price:19,min:10,step:10,features:{en:['Policy-profile extension','Activation guidance','QuAudit evidence'],es:['Extensión del perfil de políticas','Guía de activación','Evidencia QuAudit']}},
    {id:'qusoc-extra-endpoints',category:'capacity',name:{en:'QuSOC additional endpoints',es:'Endpoints adicionales QuSOC'},description:{en:'Additional monitored endpoint capacity subject to telemetry scope.',es:'Capacidad adicional de endpoints monitorizados, sujeta al alcance de telemetría.'},billing:'monthly',unit:'endpoint/month',unitEs:'endpoint/mes',price:29,min:10,step:10,features:{en:['Telemetry onboarding','Alert routing','QuFense hooks'],es:['Onboarding de telemetría','Enrutamiento de alertas','Controles QuFense']}},
    {id:'aggy-extra-users',category:'capacity',name:{en:'Additional Aggy users',es:'Usuarios adicionales de Aggy'},description:{en:'Add validated users beyond the licensed package.',es:'Añade usuarios validados por encima del paquete contratado.'},billing:'monthly',unit:'user/month',unitEs:'usuario/mes',price:15,min:5,step:5,features:{en:['QuIdentify binding','Contact and group enablement','Role profiles'],es:['Vinculación QuIdentify','Contactos y grupos','Perfiles por rol']}},
    {id:'qvit-ai-credit-1',category:'ai',name:{en:'Aggy Time AI starter · $1',es:'Tiempo IA de Aggy · $1'},description:{en:'Five governed Voice LIVE minutes after the complimentary allowance.',es:'Cinco minutos gobernados de Voz LIVE después del tiempo de cortesía.'},billing:'one_time',unit:'$1 starter pack',unitEs:'paquete inicial de $1',price:1,min:1,step:1,features:{en:['5 additional Voice LIVE minutes','1,000,000 QVit credited after confirmed payment','No automatic renewal'],es:['5 minutos adicionales de Voz LIVE','1.000.000 QVit acreditados después del pago confirmado','Sin renovación automática']}},
    {id:'qvit-ai-credit-5',category:'ai',name:{en:'Aggy Time AI · $5',es:'Tiempo IA de Aggy · $5'},description:{en:'Twenty-five additional governed Aggy Voice LIVE minutes.',es:'Veinticinco minutos adicionales gobernados de Aggy Voice LIVE.'},billing:'one_time',unit:'$5 time pack',unitEs:'paquete de tiempo de $5',price:5,min:1,step:1,features:{en:['25 additional Voice LIVE minutes','5,000,000 QVit credited after confirmed payment','No automatic renewal'],es:['25 minutos adicionales de Voz LIVE','5.000.000 QVit acreditados después del pago confirmado','Sin renovación automática']}},
    {id:'qvit-ai-credit-10',category:'ai',name:{en:'Aggy Time AI · $10',es:'Tiempo IA de Aggy · $10'},description:{en:'Fifty additional governed Aggy Voice LIVE minutes.',es:'Cincuenta minutos adicionales gobernados de Aggy Voice LIVE.'},billing:'one_time',unit:'$10 time pack',unitEs:'paquete de tiempo de $10',price:10,min:1,step:1,features:{en:['50 additional Voice LIVE minutes','10,000,000 QVit credited after confirmed payment','No automatic renewal'],es:['50 minutos adicionales de Voz LIVE','10.000.000 QVit acreditados después del pago confirmado','Sin renovación automática']}},
    {id:'qvit-ai-credit-25',category:'ai',name:{en:'Aggy Time AI · $25',es:'Tiempo IA de Aggy · $25'},description:{en:'One hundred twenty-five governed Aggy Voice LIVE minutes.',es:'Ciento veinticinco minutos gobernados de Aggy Voice LIVE.'},billing:'one_time',unit:'$25 time pack',unitEs:'paquete de tiempo de $25',price:25,min:1,step:1,features:{en:['125 additional Voice LIVE minutes','25,000,000 QVit credited after confirmed payment','No silent overdraft'],es:['125 minutos adicionales de Voz LIVE','25.000.000 QVit acreditados después del pago confirmado','Sin sobregiro silencioso']}},
    {id:'qvit-ai-credit-50',category:'ai',name:{en:'Aggy Time AI · $50',es:'Tiempo IA de Aggy · $50'},description:{en:'Two hundred fifty governed Aggy Voice LIVE minutes.',es:'Doscientos cincuenta minutos gobernados de Aggy Voice LIVE.'},billing:'one_time',unit:'$50 time pack',unitEs:'paquete de tiempo de $50',price:50,min:1,step:1,features:{en:['250 additional Voice LIVE minutes','50,000,000 QVit credited after confirmed payment','No silent overdraft'],es:['250 minutos adicionales de Voz LIVE','50.000.000 QVit acreditados después del pago confirmado','Sin sobregiro silencioso']}},
    {id:'qvit-ai-credit-100',category:'ai',name:{en:'Aggy Time AI · $100',es:'Tiempo IA de Aggy · $100'},description:{en:'Five hundred governed Aggy Voice LIVE minutes.',es:'Quinientos minutos gobernados de Aggy Voice LIVE.'},billing:'one_time',unit:'$100 time pack',unitEs:'paquete de tiempo de $100',price:100,min:1,step:1,features:{en:['500 additional Voice LIVE minutes','100,000,000 QVit credited after confirmed payment','QuPay confirmation required'],es:['500 minutos adicionales de Voz LIVE','100.000.000 QVit acreditados después del pago confirmado','Requiere confirmación QuPay']}},
    {id:'qvit-ai-credit-500',category:'ai',name:{en:'Aggy Time AI · $500',es:'Tiempo IA de Aggy · $500'},description:{en:'Two thousand five hundred governed Aggy Voice LIVE minutes for teams.',es:'Dos mil quinientos minutos gobernados de Aggy Voice LIVE para equipos.'},billing:'one_time',unit:'$500 time pack',unitEs:'paquete de tiempo de $500',price:500,min:1,step:1,features:{en:['2,500 additional Voice LIVE minutes','500,000,000 QVit credited after confirmed payment','Usage evidence'],es:['2.500 minutos adicionales de Voz LIVE','500.000.000 QVit acreditados después del pago confirmado','Evidencia de consumo']}},
    {id:'qvit-ai-credit-1000',category:'ai',name:{en:'Aggy Time AI · $1,000',es:'Tiempo IA de Aggy · $1.000'},description:{en:'Five thousand governed Aggy Voice LIVE minutes for enterprise allocation.',es:'Cinco mil minutos gobernados de Aggy Voice LIVE para asignación empresarial.'},billing:'one_time',unit:'$1,000 time pack',unitEs:'paquete de tiempo de $1.000',price:1000,min:1,step:1,features:{en:['5,000 additional Voice LIVE minutes','1,000,000,000 QVit credited after confirmed payment','Workspace allocation and usage evidence'],es:['5.000 minutos adicionales de Voz LIVE','1.000.000.000 QVit acreditados después del pago confirmado','Asignación por workspace y evidencia de consumo']}},
    {id:'human-support-ticket',category:'support',name:{en:'Human remote support ticket',es:'Ticket de soporte humano remoto'},description:{en:'One bounded request with diagnosis, response and closure evidence.',es:'Una solicitud acotada con diagnóstico, respuesta y evidencia de cierre.'},billing:'one_time',unit:'ticket',unitEs:'ticket',price:149,min:1,step:1,features:{en:['Defined scope','Remote response','Closure record'],es:['Alcance definido','Respuesta remota','Registro de cierre']}},
    {id:'specialist-remote-hour',category:'support',name:{en:'Remote specialist hour',es:'Hora de especialista remoto'},description:{en:'Scheduled engineering, security or integration assistance.',es:'Asistencia programada de ingeniería, seguridad o integraciones.'},billing:'one_time',unit:'hour',unitEs:'hora',price:195,min:1,step:1,features:{en:['Scheduled session','Technical notes','Action list'],es:['Sesión programada','Notas técnicas','Lista de acciones']}},
    {id:'live-video-support',category:'support',name:{en:'Live video support',es:'Soporte humano en vivo por video'},description:{en:'Interactive screen-sharing and guided resolution session.',es:'Sesión interactiva con pantalla compartida y resolución guiada.'},billing:'one_time',unit:'hour',unitEs:'hora',price:245,min:1,step:1,features:{en:['Live specialist','Screen-share guidance','Session summary'],es:['Especialista en vivo','Guía con pantalla compartida','Resumen de sesión']}},
    {id:'pqc-architect-hour',cryptoProfile:'E2EE/PQC',category:'consulting',name:{en:'Senior E2EE/PQC cybersecurity architect',es:'Arquitecto sénior de ciberseguridad E2EE/PQC'},description:{en:'Architecture review and advisory without production authority.',es:'Revisión de arquitectura y asesoría sin autoridad de producción.'},billing:'one_time',unit:'hour',unitEs:'hora',price:295,min:1,step:1,features:{en:['Architecture review','Risk register','Recommendations'],es:['Revisión de arquitectura','Registro de riesgos','Recomendaciones']}},
    {id:'incident-response-hour',category:'consulting',name:{en:'Incident-response assistance',es:'Asistencia de respuesta a incidentes'},description:{en:'Time-and-materials support with a four-hour minimum and explicit authorization.',es:'Soporte por tiempo y materiales con mínimo de cuatro horas y autorización explícita.'},billing:'one_time',unit:'hour',unitEs:'hora',price:350,min:4,step:1,features:{en:['Four-hour minimum','Evidence preservation','Human authorization'],es:['Mínimo de cuatro horas','Preservación de evidencia','Autorización humana']}},
    {id:'qudeploy-connector-project',category:'implementation',name:{en:'QuDeploy connector implementation',es:'Implementación de conector QuDeploy'},description:{en:'One reviewed external-provider connector and governed handoff.',es:'Un conector revisado para proveedor externo y handoff gobernado.'},billing:'one_time',unit:'project',unitEs:'proyecto',price:2490,min:1,step:1,features:{en:['Scope workshop','Connector contract','Test evidence'],es:['Taller de alcance','Contrato del conector','Evidencia de pruebas']}},
    {id:'cloud-onprem-deployment',category:'implementation',name:{en:'Cloud or on-premises deployment',es:'Deployment Cloud u On-Premise'},description:{en:'Guided installation, configuration and acceptance for one environment.',es:'Instalación, configuración y aceptación guiadas para un entorno.'},billing:'one_time',unit:'project',unitEs:'proyecto',price:3900,min:1,step:1,features:{en:['Environment plan','Guided rollout','Acceptance checklist'],es:['Plan del entorno','Despliegue guiado','Lista de aceptación']}},
    {id:'pqc-readiness-assessment',cryptoProfile:'E2EE/PQC',category:'assessment',name:{en:'E2EE/PQC readiness assessment',es:'Evaluación de preparación E2EE/PQC'},description:{en:'Repository and architecture evidence review with a prioritized gap report.',es:'Revisión de evidencia del repositorio y arquitectura con informe priorizado de brechas.'},billing:'one_time',unit:'project',unitEs:'proyecto',price:4900,min:1,step:1,features:{en:['Evidence inventory','Gap matrix','Remediation roadmap'],es:['Inventario de evidencia','Matriz de brechas','Hoja de remediación']}},
    {id:'team-security-workshop',category:'training',name:{en:'Team security workshop',es:'Taller de seguridad para equipos'},description:{en:'Instructor-led remote workshop for up to 12 participants.',es:'Taller remoto con instructor para un máximo de 12 participantes.'},billing:'one_time',unit:'workshop',unitEs:'taller',price:1490,min:1,step:1,features:{en:['Up to 12 people','Tailored agenda','Attendance evidence'],es:['Hasta 12 personas','Agenda adaptada','Evidencia de asistencia']}},
    {id:'qucfa-economics-workshop',category:'finance',name:{en:'QuCFA product-economics workshop',es:'Taller de economía de producto QuCFA'},description:{en:'Rate-card, unit-economics and governed-margin configuration.',es:'Configuración de tarifario, economía unitaria y margen gobernado.'},billing:'one_time',unit:'project',unitEs:'proyecto',price:1950,min:1,step:1,features:{en:['Rate-card design','Scenario model','Approval record'],es:['Diseño de tarifario','Modelo de escenarios','Registro de aprobación']}},
    {id:'qubank-plaid-readiness',category:'finance',name:{en:'QuBank/Plaid readiness project',es:'Proyecto de preparación QuBank/Plaid'},description:{en:'Consent, data-flow and production-readiness preparation; no bank connection included.',es:'Preparación de consentimiento, flujo de datos y producción; no incluye conexión bancaria.'},billing:'one_time',unit:'project',unitEs:'proyecto',price:2900,min:1,step:1,features:{en:['Consent map','Read-only flow','Readiness evidence'],es:['Mapa de consentimiento','Flujo de solo lectura','Evidencia de preparación']}}
  ];
  const categories={all:{en:'All',es:'Todos'},capacity:{en:'Capacity',es:'Capacidad'},ai:{en:'AI resources',es:'Recursos de IA'},support:{en:'Support',es:'Soporte'},consulting:{en:'Consulting',es:'Consultoría'},implementation:{en:'Implementation',es:'Implementación'},assessment:{en:'Assessment',es:'Evaluación'},training:{en:'Training',es:'Formación'},finance:{en:'Finance',es:'Finanzas'}};
  const activationParams=new URLSearchParams(location.search);
  let category=activationParams.get('time_ai')==='1'?'ai':'all';
  const language=()=>document.body.classList.contains('es')?'es':'en',money=value=>'$'+Number(value).toLocaleString('en-US');
  function renderFilters(){const l=language();filters.innerHTML=Object.entries(categories).map(([id,label])=>`<button type="button" data-addon-category="${id}" class="${id===category?'active':''}">${label[l]}</button>`).join('')}
  const isTimeAiPack=id=>/^qvit-ai-credit-(1|5|10|25|50|100|500|1000)$/.test(id||'');
  const addButtonLabel=service=>isTimeAiPack(service.id)?(language()==='es'?'Elegir y continuar':'Choose and continue'):(language()==='es'?'Agregar':'Add');
  const checkoutButton=()=>document.getElementById(language()==='es'?'checkoutEs':'checkout');
  function render(){const l=language(),visible=services.filter(service=>category==='all'||service.category===category);renderFilters();root.innerHTML=visible.map(service=>`<article class="addon-card" data-service="${service.id}"><header><span class="addon-category">${categories[service.category][l]}</span><span class="addon-billing">${service.billing==='monthly'?(l==='es'?'RECURRENTE':'RECURRING'):(l==='es'?'UNA VEZ':'ONE TIME')}</span></header><h3>${service.name[l]}</h3><p>${service.description[l]}</p><ul>${service.features[l].map(feature=>`<li>${feature}</li>`).join('')}</ul><div class="addon-price"><div><strong>${money(service.price)}</strong><small>${l==='es'?'por ':'per '}${l==='es'?service.unitEs:service.unit}</small></div><small>QuCFA · draft</small></div><div class="addon-controls"><input type="number" min="${service.min}" step="${service.step}" value="${service.min}" aria-label="${l==='es'?'Cantidad':'Quantity'}"><button class="btn primary" type="button" data-add-addon="${service.id}">${addButtonLabel(service)}</button></div></article>`).join('')}
  filters.addEventListener('click',event=>{const button=event.target.closest('[data-addon-category]');if(!button)return;category=button.dataset.addonCategory;render()});
  root.addEventListener('click',event=>{const button=event.target.closest('[data-add-addon]');if(!button)return;const service=services.find(item=>item.id===button.dataset.addAddon),card=button.closest('.addon-card'),input=card.querySelector('input'),quantity=Math.max(service.min,Math.floor(Number(input.value)||service.min));input.value=quantity;window.QuMarketCart.addAddon({id:service.id,name:service.name[language()],category:categories[service.category][language()],billing:service.billing,pricingUnit:language()==='es'?service.unitEs:service.unit,quantity,unitPriceUsd:service.price,scopeLabel:service.description[language()],features:service.features[language()]});card.classList.add('addon-added');button.textContent=isTimeAiPack(service.id)?(language()==='es'?'Preparando acceso…':'Preparing access…'):(language()==='es'?'Agregado ✓':'Added ✓');updateQuote({addonCount:window.QuMarketCart.snapshot().length});if(isTimeAiPack(service.id)){setTimeout(()=>checkoutButton()?.click(),0);return}setTimeout(()=>{card.classList.remove('addon-added');button.textContent=addButtonLabel(service)},1200)});
  function updateQuote(detail={}){const l=language(),items=window.QuMarketCart.snapshot(),monthly=items.filter(item=>item.billing==='monthly').reduce((sum,item)=>sum+item.totalUsd,0),servicesTotal=items.filter(item=>item.billing==='one_time').reduce((sum,item)=>sum+item.totalUsd,0),strong=quote.querySelector(`strong[data-${l}]`),small=quote.querySelector(`small[data-${l}]`);strong.textContent=items.length?(l==='es'?`${items.length} add-ons · ${money(monthly)}/mes + ${money(servicesTotal)} una vez`:`${items.length} add-ons · ${money(monthly)}/mo + ${money(servicesTotal)} one time`):(l==='es'?'No hay add-ons seleccionados':'No add-ons selected');small.textContent=items.length?(l==='es'?'QuCFA calculó el precio preliminar. Falta confirmar capacidad humana, alcance y SOW.':'QuCFA calculated the draft price. Human capacity, scope and SOW still require confirmation.'):(l==='es'?'Tarifario preliminar visible al cliente · sin disponibilidad verificada.':'Customer-facing draft rate card · availability not verified.')}
  window.addEventListener('qumarket:cart-updated',event=>updateQuote(event.detail));
  ['addonScrollCart','addonScrollCartEs'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>document.getElementById('cart').scrollIntoView({behavior:'smooth',block:'start'})));
  new MutationObserver(()=>{render();updateQuote()}).observe(document.body,{attributes:true,attributeFilter:['class']});
  render();updateQuote();
  const requestedAddon=activationParams.get('addon'),walletReference=activationParams.get('wallet_ref'),resumeTimeAiCheckout=activationParams.get('checkout')==='time_ai'&&activationParams.get('quidentify')==='verified';
  if(isTimeAiPack(requestedAddon)&&/^[A-Za-z0-9_-]{43}$/.test(walletReference||'')){
    const service=services.find(item=>item.id===requestedAddon);
    if(service){
      window.QuMarketCart.addAddon({id:service.id,name:service.name[language()],category:categories[service.category][language()],billing:service.billing,pricingUnit:language()==='es'?service.unitEs:service.unit,quantity:1,unitPriceUsd:service.price,scopeLabel:service.description[language()],features:service.features[language()]});
      document.getElementById('cart')?.scrollIntoView({behavior:'smooth',block:'start'});
      if(resumeTimeAiCheckout){
        const cleanUrl=new URL(location.href);
        cleanUrl.searchParams.delete('checkout');
        cleanUrl.searchParams.delete('quidentify');
        history.replaceState(history.state,'',cleanUrl);
        setTimeout(()=>checkoutButton()?.click(),0);
      }
    }
  }else if(activationParams.get('time_ai')==='1'){
    document.getElementById('ai-services')?.scrollIntoView({behavior:'smooth',block:'start'});
  }
})();
